# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: orderer.net
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.net
    Template:
      Count: 4
      Start: 1
    Users:
      Count: 1
