# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

vp:
  image: hyperledger/fabric-peer
  log_driver: none
  expose:
    - 7051
    - 7052
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

unit-tests:
  image: hyperledger/fabric-testenv
  links:
    - vp
    - couchdb
  environment:
    - UNIT_TEST_PEER_IP=vp
    - GO_LDFLAGS
    - OUTPUT
    - TEST_PKGS=${TEST_PKGS}
    - CORE_VM_DOCKER_ATTACHSTDOUT=true
    - JOB_TYPE=${JOB_TYPE}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${GOPATH}/src/github.com/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
  command: ./unit-test/run.sh

couchdb:
  container_name: couchdb
  image: hyperledger/fabric-couchdb
  log_driver: none
  ports:
    - "5984:5984"

